// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATZ90rNLyQCZDt2hMb_CPfEmRwyEMndpE',
    appId: '1:1011465061018:web:f6f93a930147512b1a1523',
    messagingSenderId: '1011465061018',
    projectId: 'flutterecommerceapp-3c421',
    authDomain: 'flutterecommerceapp-3c421.firebaseapp.com',
    storageBucket: 'flutterecommerceapp-3c421.firebasestorage.app',
    measurementId: 'G-J8FWDRKEP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDswz6pO-w3bxFAssjif1IOA97_BFT0vw',
    appId: '1:1011465061018:android:70dfc0ac67c0cabd1a1523',
    messagingSenderId: '1011465061018',
    projectId: 'flutterecommerceapp-3c421',
    storageBucket: 'flutterecommerceapp-3c421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUxuppHNmGv8Qrc3EMCDLcX35WPLnXTys',
    appId: '1:1011465061018:ios:a9d2ddacd3a570a41a1523',
    messagingSenderId: '1011465061018',
    projectId: 'flutterecommerceapp-3c421',
    storageBucket: 'flutterecommerceapp-3c421.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUxuppHNmGv8Qrc3EMCDLcX35WPLnXTys',
    appId: '1:1011465061018:ios:a9d2ddacd3a570a41a1523',
    messagingSenderId: '1011465061018',
    projectId: 'flutterecommerceapp-3c421',
    storageBucket: 'flutterecommerceapp-3c421.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATZ90rNLyQCZDt2hMb_CPfEmRwyEMndpE',
    appId: '1:1011465061018:web:b532e9801c58d3841a1523',
    messagingSenderId: '1011465061018',
    projectId: 'flutterecommerceapp-3c421',
    authDomain: 'flutterecommerceapp-3c421.firebaseapp.com',
    storageBucket: 'flutterecommerceapp-3c421.firebasestorage.app',
    measurementId: 'G-L62N0B6YQQ',
  );
}
